import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidenav from "@/components/(navigation)/Sidenav";
import TanstackQueryProvider from "@/providers/TanstackQueryProvider";
import MobileNav from "@/components/(navigation)/MobileNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cryptoverse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackQueryProvider>
          <div className="  flex flex-col md:flex-row gap-x-3 ">
            <div className=" hidden md:block">
              <Sidenav />
            </div>
            <div className=" md:hidden block">
              <MobileNav />
            </div>
            <div className=" md:pl-[15.5%] pt-20 md:pt-6">{children}</div>
          </div>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
